### ISSUE TITLE
ERROR: label SparseTensor is not valid

### ISSUE THREAD

**Issue by Krishna1997** [xisnu/CNN-BLSTM-CTC#2] opened 2017-10-27 11:34 UTC
Getting the following error while training on attached hdf5 file eventhough we used only ascii characters

InvalidArgumentError (see above for traceback): label SparseTensor is not valid
[val.hdf5.zip](https://github.com/xisnu/CNN-BLSTM-CTC/files/1421875/val.hdf5.zip)

: indices[3427] = [46,150] is out of bounds: need 0 <= index < [1024,150]
	 [[Node: CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=true, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](transpose/_257, _arg_Placeholder_3_0_3, _arg_Placeholder_2_0_2, _arg_Placeholder_5_0_5)]]
	 [[Node: gradients/Mean_grad/Shape_1/_269 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2173_gradients/Mean_grad/Shape_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by xisnu** [comment] 2017-10-31 05:56
I am guessing the maximum target sequence length is 150 and you are running your program with batch size 1024 as `0 <= index < [1024,150]` . But your hdf file contains only 756 samples. I am not completely sure but I think it is only a data preparation related error. Sorry for delayed reply.

**Comment by xisnu** [comment] 2018-06-08 12:49
I hope that the problem is solved. I am closing this issue.

**Closed as completed by xisnu** 2018-06-08 12:49 UTC
