### ISSUE TITLE
Extract text from test image

### ISSUE THREAD

**Issue by Krishna1997** [xisnu/CNN-BLSTM-CTC#1] opened 2017-10-26 12:18 UTC
Thanks for sharing the code. Can you please explain how to extract the text from given test images/hdf5 files.

**Comment by xisnu** [comment] 2017-10-26 12:31
@Krishna1997 Your question is not quite clear to me. If you are talking about the given data then they are not images. The procedure to read a hdf5 file can be found in the _Dataset.py_ file. Extracting text from image is an entirely different application. I am not very sure how my model is effective in that case.

**Comment by Krishna1997** [comment] 2017-10-27 11:37
Your paper is on handwriting recognition. After the model is trained, how to recognize text from a hdf5 file without target text? Basically, we would like to calculate word error rate instead of evaluating loss.

**Comment by xisnu** [comment] 2017-10-27 13:29
you can simply use `sess.run[decoded]` and feed it a dictionary only with input data. However I shall upload a more structured version of this module on 30th October 2017. You will get a ready module for predicting input sequences. Please hold on to that..

**Comment by xisnu** [comment] 2018-06-08 12:50
I hope the problem is solved. I am closing this issue.

**Closed as completed by xisnu** 2018-06-08 12:50 UTC
